version: '3'
services:
  nodejs:
    # build: .
    image: egg-ts-nodejs:v1
    ports: 
      - "7001:7001"
    # deploy:
    #   replicas: 1
    links:
      - mysql:mysql
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # ports:
    #   - "3306:3306"
    volumes:
      - ~/data/mysql/test:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

